services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/postgres
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      # Redis
      SPRING_DATA_REDIS_HOST: host.docker.internal
      SPRING_DATA_REDIS_PORT: 6379
      # Minio
      MINIO_ENDPOINT: http://host.docker.internal:9000
      MINIO_ACCESSKEY: user
      MINIO_SECRETKEY: password
      MINIO_BUCKETNAME: corpbucket